services:
  document-xml-processor-api:
    build: DocumentXMLProcessorAPI/
    container_name: document-xml-processor-api
    command: dotnet DocumentXmlProcessorAPI.dll
    ports:
      - 5000:80
  old-file-wathcer:
    build: OldFileWatcher/
    container_name: old-file-wathcer
    command: dotnet OldFIleWatcher.dll
  pdf-processing:
    build: PdfProcessor/
    container_name: pdf-processing
    command: dotnet PdfProcessor.dll
  xslt-processing:
    build: XsltProcessor/
    container_name: xslt-processing
    command: dotnet XsltProcessor.dll
    