FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /source

# Copy .csproj files for caching
COPY ./DocumentXmlProcessorContext/DocumentXmlProcessorContext.csproj ./DocumentXmlProcessorContext/
COPY ./ProcessingCommon/ProcessingCommon.csproj ./ProcessingCommon/
COPY ./DocumentXmlProcessorAPI/DocumentXmlProcessorAPI.csproj ./DocumentXmlProcessorAPI/
COPY nuget.config ./

# Restore dependencies
RUN dotnet restore DocumentXmlProcessorAPI/DocumentXmlProcessorAPI.csproj

# Copy source code after restore
COPY ./DocumentXmlProcessorContext ./DocumentXmlProcessorContext/
COPY ./ProcessingCommon ./ProcessingCommon/
COPY ./DocumentXmlProcessorAPI ./DocumentXmlProcessorAPI/

WORKDIR /source/DocumentXmlProcessorAPI
RUN dotnet publish DocumentXmlProcessorAPI.csproj -c $BUILD_CONFIGURATION -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app ./
COPY ./DocumentXmlProcessorAPI/appsettings.json ./

ENTRYPOINT ["dotnet", "DocumentXmlProcessorAPI.dll"]
