version: '3.3'
services:
    speedtest:
       environment:
           - ENABLE_LETSENCRYPT=True
           - DOMAIN_NAME=speedtest.tbc.su
           - USER_EMAIL=speedtest@tbc.su
       restart: unless-stopped
       container_name: openspeedtest
       ports:
            - '80:3000'
            - '443:3001'
       image: openspeedtest/latest
