// <auto-generated />
using System;
using System.Text.Json;
using DocumentXmlProcessorContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentXmlProcessorContext.Migrations
{
    [DbContext(typeof(DocumentProcessorContext))]
    partial class DocumentProcessorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentXmlProcessorContext.Entity.ProcessingFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalData")
                        .HasColumnType("jsonb");

                    b.Property<string>("CallbackParams")
                        .HasColumnType("text");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateCompleteProcessing")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProcessingFileDataId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProcessingFiles");
                });

            modelBuilder.Entity("DocumentXmlProcessorContext.Entity.ProcessingFileData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("HtmlPath")
                        .HasColumnType("text");

                    b.Property<double?>("HtmlTimeProcessing")
                        .HasColumnType("double precision");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<double?>("PdfTimeProcessing")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProcessingFileId")
                        .HasColumnType("uuid");

                    b.Property<string>("XmlPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcessingFilesData");
                });

            modelBuilder.Entity("DocumentXmlProcessorContext.Entity.ProcessingFileError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessingFileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingFileId");

                    b.ToTable("ProcessingFileErrors");
                });

            modelBuilder.Entity("DocumentXmlProcessorContext.Entity.ProcessingFileData", b =>
                {
                    b.HasOne("DocumentXmlProcessorContext.Entity.ProcessingFile", "ProcessingFile")
                        .WithOne("ProcessingFileData")
                        .HasForeignKey("DocumentXmlProcessorContext.Entity.ProcessingFileData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingFile");
                });

            modelBuilder.Entity("DocumentXmlProcessorContext.Entity.ProcessingFileError", b =>
                {
                    b.HasOne("DocumentXmlProcessorContext.Entity.ProcessingFile", "ProcessingFile")
                        .WithMany("ProcessingFileErrors")
                        .HasForeignKey("ProcessingFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingFile");
                });

            modelBuilder.Entity("DocumentXmlProcessorContext.Entity.ProcessingFile", b =>
                {
                    b.Navigation("ProcessingFileData")
                        .IsRequired();

                    b.Navigation("ProcessingFileErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
