version: '3.3'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - /docker-data/registry:/var/lib/registry
      - /docker-data/certs:/certs
    labels:
      container_name: registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
